### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by zzzzzzzzzzzq** [chanmaoganda/LoLClientHelper#1]
怎么运行程序就这样了。。。（只开了英雄联盟客户端 没匹配游戏）![image](https://github.com/chanmaoganda/LoLClientHelper/assets/114342119/4efd75c6-f09e-44fc-9723-6fe281c5b73e)

**Comment by zzzzzzzzzzzq** [comment]
> 怎么运行程序就这样了。。。（只开了英雄联盟客户端 没匹配游戏）![图像](https://private-user-images.githubusercontent.com/114342119/347360441-4efd75c6-f09e-44fc-9723-6fe281c5b73e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDY5NjYsIm5iZiI6MTcyMDYwNjY2NiwicGF0aCI6Ii8xMTQzNDIxMTkvMzQ3MzYwNDQxLTRlZmQ3NWM2LWYwOWUtNDRmYy05NzIzLTZmZTI4MWM1YjczZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMDE3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzliZjY5Y2ExZWEzODQyZWIzZDQ2Yzg1NTczNGU0NWVkNDFkZjQ3NzBiNjJlNGMzY2ZhYzdhODA1OGI3YWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R12w0tIY07PoZlWmb0aD1s6znekVQ0H7HUKyIrEGO6E)

ok了 我忘记用管理员身份运行了

**Comment by chanmaoganda** [comment]
管理员运行也这样吗？

**Comment by chanmaoganda** [comment]
这个不用管理员运行是没法读取到进程启动参数的😊
